###############################################################################
# Go
###############################################################################
[[language]]
name = "go"
auto-format = true
formatter = { command = "goimports" }
language-servers = ["gopls", "golangci-lint-lsp"]
[language.debugger]
name = "go"
transport = "tcp"
command = "dlv"
args = ["dap"]
port-arg = "--listen=127.0.0.1:{}"

[[language.debugger.templates]]
name = "source"
request = "launch"
completion = [{ name = "entrypoint", completion = "filename", default = "." }]
args = { mode = "debug", program = "{0}" }

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [{ name = "binary", completion = "filename" }]
args = { mode = "exec", program = "{0}" }

[[language.debugger.templates]]
name = "test"
request = "launch"
completion = [{ name = "tests", completion = "filename", default = "." }]
args = { mode = "test", program = "{0}" }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = [{ name = "process", completion = "pid" }]
args = { mode = "local", processId = "{0}" }

[language-server.gopls]
command = "gopls"

[language-server.gopls.config.hints]
assignVariableTypes = true
compositeLiteralFields = true
compositeLiteralTypes = true
constantValues = true
functionTypeParameters = true
parameterNames = true
rangeVariableTypes = true

[language-server.golangci-lint-lsp]
command = "golangci-lint-langserver"

[language-server.golangci-lint-lsp.config]
command = ["golangci-lint", "run", "--output.text.path=stdout", "--issues-exit-code=1"]

###############################################################################
# Terraform / HCL
###############################################################################
[[language]]
name = "hcl"
language-servers = ["terraform-ls", "efm"]
auto-format = true
file-types = ["tf", "tfvars"]
roots = [".terraform", "*.tf"]

[[language]]
name = "tfvars"
language-servers = ["terraform-ls", "efm"]
auto-format = true

[language-server.terraform-ls]
command = "terraform-ls"
args = ["serve"]

[language-server.efm]
command = "efm-langserver"

###############################################################################
# TOML / YAML (nice to have)
###############################################################################
[[language]]
name = "toml"
auto-format = true

[[language]]
name = "yaml"
auto-format = true
